site_name: PnP/generator-SPFx
nav:
  - Home: 'index.md'
  - Feature: features.md
  - Usage: usage.md
  - How Tos: howtos/index.md
  - Compose:
    - General: compose/index.md
    - Prompting: compose/prompting.md
    - Dependencies for addons: compose/add-addons.md
    - Inject dependencies: compose/custgen-dependencies.md
  - Recipes:
    - Inject gulp tasks: 'recipes/inject-gulp-tasks.md'
    - Run Install: 'recipes/run-install.md'
    - Deploy Custom Code: 'recipes/deploy-custom-code.md'
  - FAQ : 'faq.md'
  - Release Notes: 'release-notes.md'
  - Known Issues: 'known-issues.md'
  - Contribution Guidelines: 'contribution-guidelines.md'
  - License: 'license.md'
  - About: 'about.md'
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'blue grey'
  logo: 'assets/logo.svg'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
google_analytics:
  - 'UA-124825047-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/pnpspfx'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
site_url: https://pnp.github.io/generator-spfx/
repo_url: http://github.com/pnp/generator-spfx
edit_uri: blob/master/docs/
