# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/generator-spfx
  docker:
    - image: circleci/node:8.11.2

version: 2
jobs:
  build:
    <<: *defaults    

    steps:
      - checkout
      - attach_workspace:
          at: ~/generator-spfx
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/generator-spfx
      - run:
          name: Testing SPO
          command: npm run test-spo
      - run:
          name: Testing On Prem
          command: npm run test-onprem
      - run:
          name: Testing On Handlebars
          command: npm run test-handlebars
      - run:
          name: Testing On React
          command: npm run test-react
      - run:
          name: Testing On Knockout
          command: npm run test-kockout
    deploy_docs:
        working_directory: ~/generator-spfx/
        docker:
        - image: circleci/python:2.7-jessie-node
        steps:
        - attach_workspace:
            at: ~/office365-cli
        - add_ssh_keys:
            fingerprints:
                - "bc:b2:e7:2f:ce:45:b9:c3:9f:1d:15:4c:a3:6c:14:71"
        - run:
            name: Install MkDocs
            command: sudo pip install mkdocs
        - run:
            name: Install MkDocs theme
            command: sudo pip install mkdocs-material
        - run:
            name: Avoid hosts unknown for github
            command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        - run:
            name: Build docs
            command: mkdocs gh-deploy