version: 2
defaults: &defaults
  working_directory: ~/generator-spfx
  docker:
    - image: circleci/node:8.11.2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/generator-spfx
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Restore dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run install
          command: npm install
      - persist_to_workspace:
          root: .
          paths: ["."]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/generator-spfx
      - run:
          name: Test Run All
          command: npm run test
    #   - run:
    #       name: Test React
    #       command: npm run test-react
    #   - run:
    #       name: Test Handlebars
    #       command: npm run test-handlebars
      - store_artifacts:
          path: testresult
  deploy_docs:
    version: 2
    docker:
      - image: circleci/python:2.7-jessie-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/generator-spfx/docs
      - add_ssh_keys:
          fingerprints:
            - "01:12:96:33:52:ca:c2:c7:c6:29:7a:1a:43:85:cf:e9"
      - run:
          name: Install MkDocs
          command: sudo pip install mkdocs
      - run:
          name: Install MkDocs theme
          command: sudo pip install mkdocs-material
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Build docs
          command: mkdocs gh-deploy --remote-branch gh-pages
  publish:
    <<: *defaults
    branches:
        ignore:
            - gh-pages
    steps:
      - attach_workspace:
          at: ~/generator-spfx
      - run:
          name: Write .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: npm publish --access public
workflows:
  version: 2
  testing:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
      - deploy_docs:
          filters:
            branches:
              ignore: gh-pages
              only: master
